server:
  port: ${SERVER_PORT}
  module2:
    url: ${MODULE2_SERVER_URL}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    path: /module1
    operations-sorter: method
  api-docs:
    path: /module1