server:
  port: ${SERVER_PORT}
spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CONSUMER_DATASOURCE_URL}
    username: ${CONSUMER_DATASOURCE_USERNAME}
    password: ${CONSUMER_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
springdoc:
  swagger-ui:
    path: /consumer/swagger-ui.html
  api-docs:
    path: /consumer