server:
  port: ${SERVER_PORT}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MODULE2_DATASOURCE_URL}
    username: ${MODULE2_DATASOURCE_USERNAME}
    password: ${MODULE2_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
